### ISSUE TITLE
This mod combined with a newer version of Java causes the SimpleVoicechat mod to crash.

### ISSUE THREAD

**Issue by IdotMaster1** [hammcmod/RadioCraft#9]
Tested on Java 21. When this mod is removed, it starts up fine. 

Crash report:
[crash-2024-08-19_23.43.29-fml.txt](https://github.com/user-attachments/files/16665590/crash-2024-08-19_23.43.29-fml.txt)

**Comment by jrddunbr** [comment]
If I had to guess, mixins don't work with Java 21 and Minecraft 1.19.3.

Does it work if you use Java 17, which I'm pretty sure is the version of Java that Minecraft 1.19.3 was developed for?

**Comment by IdotMaster1** [comment]
It does work with Java 17.

**Comment by jrddunbr** [comment]
I don't think that is something that can be fixed for 1.19.3, because the Radiocraft team doesn't write the mixin library.

I'm currently working on porting the mod to 1.21.1 NeoForge, which does work on Java 21.

**Comment by jrddunbr** [comment]
We ported to Minecraft 1.21 so you may be able to try on that. We are no longer supporting 1.19.3.
